[book]
authors = ["anupama-pathirage"]
language = "en"
multilingual = false
src = "src"
title = "Learning Ballerina"

[output.html]
theme = "mytheme"
default-theme = "light"
preferred-dark-theme = "navy"