name: Test Samples

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  test:
    env:
      JBAL_VERSION: swan-lake-beta6
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Download jBallerina deb
      run: |
          curl -L "https://github.com/ballerina-platform/ballerina-distribution/releases/download/v$JBAL_VERSION/ballerina-linux-installer-x64-$JBAL_VERSION.deb" > $HOME/ballerina-linux-installer-x64-$JBAL_VERSION.deb
    - name: Install jBallerina deb
      run: |
        sudo dpkg -i $HOME/ballerina-linux-installer-x64-$JBAL_VERSION.deb
        echo "/usr/lib/ballerina/bin" >> $GITHUB_PATH
        echo "/usr/lib/ballerina/dependencies/jdk-11.0.8+10-jre/bin/java" >> $GITHUB_PATH
    - name: Run sample
      id: run_sample
      run: |
          programOutput=$(bal run code/float.bal)
          programOutput="${programOutput//'%'/'%25'}"
          programOutput="${programOutput//$'\n'/'%0A'}"
          programOutput="${programOutput//$'\r'/'%0D'}"
          echo "::set-output name=PROGRAM_OUT::$programOutput"

          fileContent=$(cat code/float.bash)
          fileContent="${fileContent//'%'/'%25'}"
          fileContent="${fileContent//$'\n'/'%0A'}"
          fileContent="${fileContent//$'\r'/'%0D'}"
          echo "::set-output name=FILE_OUT::$fileContent"

    - name: Test sample 
      run: |
          echo ${{ needs.test.outputs.PROGRAM_OUT }}
          echo ${{ needs.test.outputs.FILE_OUT }}
          
          echo "---------------\n"